/*
 * TRAC Controller API
 * This is a simple API for the connecting to the Two Rivers Activity Centers waterpark control system. It should only be accessable from within the internal network.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: brandan.schmitz@uj.edu
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package net.celestialdata.client.api;

import net.celestialdata.client.ApiException;
import net.celestialdata.client.model.ArrayOfStatus;
import net.celestialdata.client.model.FeatureStatus;
import org.junit.Test;
import org.junit.Ignore;

/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Get the status of all the park features
     *
     * Get the status of all the various waterpark features and return it as a JSON array.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getStatusTest() throws ApiException {
        ArrayOfStatus response = api.getStatus();

        // TODO: test validations
    }
    /**
     * Toggle a water feature on or off
     *
     * Toggle a water feature on or off. It will be switched to whatever state it is not currently in.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void toggleFeatureTest() throws ApiException {
        String name = null;
        FeatureStatus response = api.toggleFeature(name);

        // TODO: test validations
    }
}
